name: 'gap-prod'
services:
    laravel:
        restart: always
        build:
            context: ./laravel
            dockerfile: Dockerfile.prod
            args:
                WWWGROUP: '${WWWGROUP}'
        image: laravel
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        env_file:
            - .env
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            WWWGROUP: '${WWWGROUP:-1000}'
            PWD: '${PWD:-/var/www/html}'
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            FORWARD_DB_PORT: '${FORWARD_DB_PORT:-5432}'
            PRIVATE_KEY_256: '${PRIVATE_KEY_256:-secret}'
            PUBLIC_KEY_RSA_B64: '${PUBLIC_KEY_RSA_B64}'
            PRIVATE_KEY_GITHUB: '${PRIVATE_KEY_GITHUB}'
            GITHUB_BUCKET_USER: '${GITHUB_BUCKET_USER}'
            GITHUB_BUCKET_REP: '${GITHUB_BUCKET_REP}'
            EMAIL_SUPPORT: '${EMAIL_SUPPORT}'
            APP_ENV: 'prod'
        volumes:
            - './laravel:/app'
            - /app/vendor
        networks:
            - sail
        depends_on:
            - pgsql
    pgsql:
        restart: always
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    vue:
        restart: always
        build:
            context: ./vue
            dockerfile: Dockerfile.prod
            args: 
                CHOKIDAR_USEPOLLING: 'true'
                VUE_APP_API_URL: '${VUE_APP_API_URL}'
                VUE_APP_TRACKER_LOCALIZATION: '${VUE_APP_TRACKER_LOCALIZATION}'
                VUE_APP_ROUTE_CALCULATOR: '${VUE_APP_ROUTE_CALCULATOR}'
                VUE_APP_CARRIER_COMPLETE_NAME: '${VUE_APP_CARRIER_COMPLETE_NAME}'
                VUE_APP_CARRIER_PARCIAL_NAME: '${VUE_APP_CARRIER_PARCIAL_NAME}'
                VUE_APP_CARRIER_CNPJ: '${VUE_APP_CARRIER_CNPJ}'
                VUE_APP_CARRIER_ADDRESS: '${VUE_APP_CARRIER_ADDRESS}'
                VUE_APP_CARRIER_CEP: '${VUE_APP_CARRIER_CEP}'
                VUE_APP_CARRIER_TELEPHONE: '${VUE_APP_CARRIER_TELEPHONE}'
                VUE_APP_CARRIER_CELLPHONE: '${VUE_APP_CARRIER_CELLPHONE}'
                VUE_APP_SITE_DESCRIPTION: '${VUE_APP_SITE_DESCRIPTION}'
        image: vue
        volumes:
            - './vue:/app'
            - /app/node_modules
        networks:
            - sail
    mailpit:
        image: 'axllent/mailpit:latest'
        networks:
            - sail
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.prod
        ports:
            - '80:80'
            - '443:443'
        environment:
            DOMAIN: '${DOMAIN}'
            EMAIL_SUPPORT: '${EMAIL_SUPPORT}'
            STAGING_URL: '${STAGING_URL}'
        volumes:
            - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
            - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
            - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
            - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
        depends_on:
            - laravel
            - vue
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
