FROM nginx:latest

COPY nginx.https.conf /etc/nginx/conf.d/default.conf.template

COPY docker-entrypoint.sh /
RUN apt update && \ 
    apt install certbot python3-certbot-nginx -y && \ 
    chmod +x /docker-entrypoint.sh
EXPOSE 80 443
ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]