name: Deploy Production

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy-production:
        runs-on: ubuntu-latest
        environment:
            name: prod
        steps:
            - name: Initialize
              run: echo Building the app

            - name: Setup SSH Agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

            - name: Configure SSH
              run: |
                set -e
                mkdir -p ~/.ssh
                ssh-keyscan -H ${{ secrets.SERVER_IP_PUBLIC }} >> ~/.ssh/known_hosts

            - name: Deploy Application
              run: |
                set -e
                ssh ${{ secrets.REMOTE_USER }}@${{ secrets.SERVER_IP_PUBLIC }} '
                    cd ${{ secrets.TARGET }} && \
                    git fetch origin main && \
                    git reset --hard origin/main && \
                    docker compose -f docker-compose.prod.yml up -d --build
                '

            - name: Run Database Migrations
              run: |
                set -e
                ssh ${{ secrets.REMOTE_USER }}@${{ secrets.SERVER_IP_PUBLIC }} 'docker compose -f ${{ secrets.TARGET }}/docker-compose.prod.yml exec -T laravel php artisan migrate'
            - name: Perform Health Check
              run: |
                set -e
                curl -sSf ${{ secrets.PRODUCTION_URL }} || exit 1
