name: WorkFlow Main

on: pull_request
# on: 
#     pull_request:
#         branches: [main]
#     workflow_dispatch:

jobs:
  test-production:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.dev.yml"

      - name: Execute tests in the running services
        run: |
          docker compose -f docker-compose.dev.yml exec -T laravel php artisan migrate